name: McMongoAuth
main: ru.mikotocraft.mcmongoauth.McMongoAuth
version: 1.0
commands:
   login:
      description: Command used to login to server
      usage: /login [password]
   logout:
      description: Command used to logout of server
      usage: /logout
   register:
      description: Command used to register with the server
      usage: /register [password]
   unregister:
      description: Command used to unregsiter with the server
      usage: /unregister [password]
   changepass:
      description: Command used to change password
      usage: /changepass [old password] [new password]